---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:  
    - name: example using security group rule descriptions
      ec2_group:
        name: "test-group"
        description: sg with rule descriptions
        vpc_id: vpc-d12778b6
        #profile: "{{ aws_profile }}"
        region: ap-southeast-2
        rules:
          - proto: tcp
            ports:
            - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on port ssh
