# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: false

  vars: 
      ami_id: ami-0c9d48b5db609ad6e
      region: ap-southeast-2

  tasks:
    - name: Provision a set instances
      ec2:
        key_name: demo-ec2-key
        group: demo-security-group
        instance_type: t3.micro
        image: "{{ ami_id }}"
        wait: true
        exact_count: 1
        region: "{{ region }}"
        count_tag:
          Name: Demo
        instance_tags:
          Name: Demo
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      loop: "{{ ec2.instances }}"

      