---
- name: install and start apache
  hosts: web
  remote_user: justin
  become_method: sudo
  become_user: root
  vars:
    http_port: 80
    max_clients: 200

  tasks:
  - name: install httpd
    yum: name=httpd state=latest
  - name: write apache config file
    template: src=srv/httpd.j2 dest=/etc/httpd.config
    notify:
    - restart apache
  - name: start httpd
    service: name=httpd state=running
  
  handlers:
  - name: restart apache
    service: name=httpd state=restarted
    